CSK/urls.py
from django.urls import path
from CSK.views import *
app_name='CSK'
urlpatterns=[
    path('Dhoni/',Dhoni,name='Dhoni')
]

RCB/urls.py
from django.urls import path
from RCB.views import *
app_name='RCB'
urlpatterns=[
    path('Virat/',Virat,name='Virat')
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import CSK,RCB
urlpatterns = [
    path('admin/', admin.site.urls),
    path('CSK/',include('CSK.urls')),
    path('RCB/',include('RCB.urls')),
]

CSK/models.py
from django.db import models

# Create your models here.

RCB/models.py
from django.db import models

# Create your models here.

CSK/views.py
from django.shortcuts import render

# Create your views here.
def Dhoni(request):
    return render(request,'Dhoni.html')

RCB/views.py
from django.shortcuts import render

# Create your views here.

def Virat(request):
    return render(request,'Virat.html')

templates/Dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    <h1>Dhoni Html page</h1>
    <h1> this is CSK Application</h1>
    <a href="{% url 'RCB:Virat' %}">Navigate to Rcb team</a>
</center>
</body>
</html>

templates/Virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is Virat page</h1>
        <h1>this RCB application</h1>
        <a href="{% url 'CSK:Dhoni' %}">Naviagtion to CSK Team</a>
    </center>
</body>
</html>